// Generated by scripts/split-collected-segments.mjs. Do not edit.
export const COLLECTED_TOTAL_TAGS = 51476;
export const COLLECTED_PHRASES_SEGMENT = 'seg-phrases';
export const COLLECTED_SEGMENTS = [
  {
    "id": "seg-000",
    "groups": [
      "角色与作品"
    ],
    "count": 2403
  },
  {
    "id": "seg-001",
    "groups": [
      "角色与作品"
    ],
    "count": 2403
  },
  {
    "id": "seg-002",
    "groups": [
      "角色与作品"
    ],
    "count": 2403
  },
  {
    "id": "seg-003",
    "groups": [
      "角色与作品"
    ],
    "count": 2403
  },
  {
    "id": "seg-004",
    "groups": [
      "角色与作品"
    ],
    "count": 2403
  },
  {
    "id": "seg-005",
    "groups": [
      "角色与作品"
    ],
    "count": 2403
  },
  {
    "id": "seg-006",
    "groups": [
      "角色与作品"
    ],
    "count": 2403
  },
  {
    "id": "seg-007",
    "groups": [
      "角色与作品"
    ],
    "count": 2403
  },
  {
    "id": "seg-008",
    "groups": [
      "角色与作品"
    ],
    "count": 2403
  },
  {
    "id": "seg-009",
    "groups": [
      "角色与作品"
    ],
    "count": 2403
  },
  {
    "id": "seg-010",
    "groups": [
      "角色与作品"
    ],
    "count": 2403
  },
  {
    "id": "seg-011",
    "groups": [
      "角色与作品"
    ],
    "count": 2403
  },
  {
    "id": "seg-012",
    "groups": [
      "角色与作品"
    ],
    "count": 2403
  },
  {
    "id": "seg-013",
    "groups": [
      "角色与作品"
    ],
    "count": 2403
  },
  {
    "id": "seg-014",
    "groups": [
      "角色与作品"
    ],
    "count": 2391
  },
  {
    "id": "seg-015",
    "groups": [
      "服装"
    ],
    "count": 2297
  },
  {
    "id": "seg-016",
    "groups": [
      "服装"
    ],
    "count": 2297
  },
  {
    "id": "seg-017",
    "groups": [
      "身体特征"
    ],
    "count": 1757
  },
  {
    "id": "seg-018",
    "groups": [
      "身体特征"
    ],
    "count": 1757
  },
  {
    "id": "seg-019",
    "groups": [
      "面部特征"
    ],
    "count": 1101
  },
  {
    "id": "seg-020",
    "groups": [
      "人物动作"
    ],
    "count": 1054
  },
  {
    "id": "seg-021",
    "groups": [
      "发型"
    ],
    "count": 898
  },
  {
    "id": "seg-022",
    "groups": [
      "艺术风格"
    ],
    "count": 371
  },
  {
    "id": "seg-023",
    "groups": [
      "敏感分级"
    ],
    "count": 359
  },
  {
    "id": "seg-024",
    "groups": [
      "构图与镜头"
    ],
    "count": 273
  },
  {
    "id": "seg-025",
    "groups": [
      "食物 · sweets"
    ],
    "count": 201
  },
  {
    "id": "seg-026",
    "groups": [
      "花卉植物"
    ],
    "count": 182
  },
  {
    "id": "seg-027",
    "groups": [
      "人物类型"
    ],
    "count": 153
  },
  {
    "id": "seg-028",
    "groups": [
      "画面格式"
    ],
    "count": 120
  },
  {
    "id": "seg-029",
    "groups": [
      "上半身"
    ],
    "count": 97
  },
  {
    "id": "seg-030",
    "groups": [
      "食物 · meal"
    ],
    "count": 97
  },
  {
    "id": "seg-031",
    "groups": [
      "10_物品道具/武器"
    ],
    "count": 95
  },
  {
    "id": "seg-032",
    "groups": [
      "建筑"
    ],
    "count": 94
  },
  {
    "id": "seg-033",
    "groups": [
      "11_动植物/动物"
    ],
    "count": 92
  },
  {
    "id": "seg-034",
    "groups": [
      "食物 · fruit"
    ],
    "count": 89
  },
  {
    "id": "seg-035",
    "groups": [
      "头部装饰"
    ],
    "count": 83
  },
  {
    "id": "seg-036",
    "groups": [
      "下半身"
    ],
    "count": 83
  },
  {
    "id": "seg-037",
    "groups": [
      "3_人物主体/职业身份"
    ],
    "count": 81
  },
  {
    "id": "seg-038",
    "groups": [
      "符号/特殊标签"
    ],
    "count": 81
  },
  {
    "id": "seg-039",
    "groups": [
      "10_物品道具/日常物品"
    ],
    "count": 79
  },
  {
    "id": "seg-040",
    "groups": [
      "9_动作姿态/动态动作"
    ],
    "count": 70
  },
  {
    "id": "seg-041",
    "groups": [
      "食物 · vegetable"
    ],
    "count": 69
  },
  {
    "id": "seg-042",
    "groups": [
      "未分类"
    ],
    "count": 66
  },
  {
    "id": "seg-043",
    "groups": [
      "鞋袜"
    ],
    "count": 66
  },
  {
    "id": "seg-044",
    "groups": [
      "颈部"
    ],
    "count": 65
  },
  {
    "id": "seg-045",
    "groups": [
      "食物 · drink"
    ],
    "count": 62
  },
  {
    "id": "seg-046",
    "groups": [
      "室外环境"
    ],
    "count": 61
  },
  {
    "id": "seg-047",
    "groups": [
      "耳朵"
    ],
    "count": 54
  },
  {
    "id": "seg-048",
    "groups": [
      "食物 · breads"
    ],
    "count": 53
  },
  {
    "id": "seg-049",
    "groups": [
      "食物 · meat"
    ],
    "count": 53
  },
  {
    "id": "seg-050",
    "groups": [
      "构图"
    ],
    "count": 51
  },
  {
    "id": "seg-051",
    "groups": [
      "物品"
    ],
    "count": 45
  },
  {
    "id": "seg-052",
    "groups": [
      "自然环境"
    ],
    "count": 45
  },
  {
    "id": "seg-053",
    "groups": [
      "3_人物主体/种族"
    ],
    "count": 44
  },
  {
    "id": "seg-054",
    "groups": [
      "视觉效果"
    ],
    "count": 40
  },
  {
    "id": "seg-055",
    "groups": [
      "1_艺术风格/现代潮流"
    ],
    "count": 38
  },
  {
    "id": "seg-056",
    "groups": [
      "5_五官表情/表情"
    ],
    "count": 38
  },
  {
    "id": "seg-057",
    "groups": [
      "7_场景背景/时间天气"
    ],
    "count": 36
  },
  {
    "id": "seg-058",
    "groups": [
      "室内环境"
    ],
    "count": 36
  },
  {
    "id": "seg-059",
    "groups": [
      "3_人物主体/体型年龄"
    ],
    "count": 33
  },
  {
    "id": "seg-060",
    "groups": [
      "1_艺术风格/经典流派"
    ],
    "count": 30
  },
  {
    "id": "seg-061",
    "groups": [
      "艺术表现"
    ],
    "count": 30
  },
  {
    "id": "seg-062",
    "groups": [
      "10_物品道具/特效元素"
    ],
    "count": 27
  },
  {
    "id": "seg-063",
    "groups": [
      "方向与视线"
    ],
    "count": 27
  },
  {
    "id": "seg-064",
    "groups": [
      "色彩"
    ],
    "count": 27
  },
  {
    "id": "seg-065",
    "groups": [
      "1_艺术风格/绘画风格"
    ],
    "count": 24
  },
  {
    "id": "seg-066",
    "groups": [
      "12_负面提示/画质缺陷"
    ],
    "count": 24
  },
  {
    "id": "seg-067",
    "groups": [
      "6_服装配饰/配饰"
    ],
    "count": 24
  },
  {
    "id": "seg-068",
    "groups": [
      "食物 · dairy"
    ],
    "count": 23
  },
  {
    "id": "seg-069",
    "groups": [
      "11_动植物/植物"
    ],
    "count": 22
  },
  {
    "id": "seg-070",
    "groups": [
      "透视与视角"
    ],
    "count": 21
  },
  {
    "id": "seg-071",
    "groups": [
      "7_场景背景/自然场景"
    ],
    "count": 19
  },
  {
    "id": "seg-072",
    "groups": [
      "天空天气"
    ],
    "count": 19
  },
  {
    "id": "seg-073",
    "groups": [
      "3_人物主体/人数性别"
    ],
    "count": 18
  },
  {
    "id": "seg-074",
    "groups": [
      "背景"
    ],
    "count": 18
  },
  {
    "id": "seg-075",
    "groups": [
      "食物 · condiments"
    ],
    "count": 18
  },
  {
    "id": "seg-076",
    "groups": [
      "身体装饰"
    ],
    "count": 17
  },
  {
    "id": "seg-077",
    "groups": [
      "7_场景背景/室内场景"
    ],
    "count": 16
  },
  {
    "id": "seg-078",
    "groups": [
      "1_艺术风格/数字风格"
    ],
    "count": 15
  },
  {
    "id": "seg-079",
    "groups": [
      "12_负面提示/内容过滤"
    ],
    "count": 15
  },
  {
    "id": "seg-080",
    "groups": [
      "6_服装配饰/上身服装"
    ],
    "count": 15
  },
  {
    "id": "seg-081",
    "groups": [
      "6_服装配饰/鞋袜"
    ],
    "count": 15
  },
  {
    "id": "seg-082",
    "groups": [
      "5_五官表情/面部细节"
    ],
    "count": 14
  },
  {
    "id": "seg-083",
    "groups": [
      "7_场景背景/城市建筑"
    ],
    "count": 14
  },
  {
    "id": "seg-084",
    "groups": [
      "9_动作姿态/手部姿态"
    ],
    "count": 13
  },
  {
    "id": "seg-085",
    "groups": [
      "画质"
    ],
    "count": 12
  },
  {
    "id": "seg-086",
    "groups": [
      "6_服装配饰/下身服装"
    ],
    "count": 11
  },
  {
    "id": "seg-087",
    "groups": [
      "8_色彩光线/光照"
    ],
    "count": 10
  },
  {
    "id": "seg-088",
    "groups": [
      "画面遮挡"
    ],
    "count": 10
  },
  {
    "id": "seg-089",
    "groups": [
      "艺术风格/绘画媒介"
    ],
    "count": 10
  },
  {
    "id": "seg-090",
    "groups": [
      "0_画质基础/品质词"
    ],
    "count": 8
  },
  {
    "id": "seg-091",
    "groups": [
      "8_色彩光线/色调"
    ],
    "count": 8
  },
  {
    "id": "seg-092",
    "groups": [
      "画面元素"
    ],
    "count": 8
  },
  {
    "id": "seg-093",
    "groups": [
      "NSFW/暴露程度"
    ],
    "count": 7
  },
  {
    "id": "seg-094",
    "groups": [
      "2_构图视角/构图方式"
    ],
    "count": 6
  },
  {
    "id": "seg-095",
    "groups": [
      "城市"
    ],
    "count": 6
  },
  {
    "id": "seg-096",
    "groups": [
      "9_动作姿态/站坐姿态"
    ],
    "count": 5
  },
  {
    "id": "seg-097",
    "groups": [
      "2_构图视角/视角方向"
    ],
    "count": 3
  },
  {
    "id": "seg-098",
    "groups": [
      "4_发型发色/发型"
    ],
    "count": 3
  },
  {
    "id": "seg-099",
    "groups": [
      "艺术风格/数字艺术"
    ],
    "count": 3
  },
  {
    "id": "seg-100",
    "groups": [
      "NSFW/暧昧氛围"
    ],
    "count": 3
  },
  {
    "id": "seg-101",
    "groups": [
      "0_画质基础/渲染效果"
    ],
    "count": 2
  },
  {
    "id": "seg-102",
    "groups": [
      "2_构图视角/镜头距离"
    ],
    "count": 2
  },
  {
    "id": "seg-103",
    "groups": [
      "5_五官表情/眼睛"
    ],
    "count": 2
  },
  {
    "id": "seg-104",
    "groups": [
      "NSFW/亲密互动"
    ],
    "count": 2
  },
  {
    "id": "seg-105",
    "groups": [
      "NSFW/氛围暗示"
    ],
    "count": 1
  },
  {
    "id": "seg-phrases",
    "groups": [],
    "count": 7929
  }
];
export const COLLECTED_TAG_GROUPS = {
  "0_画质基础/品质词": {
    "count": 8,
    "segments": [
      "seg-090"
    ]
  },
  "0_画质基础/渲染效果": {
    "count": 2,
    "segments": [
      "seg-101"
    ]
  },
  "1_艺术风格/绘画风格": {
    "count": 24,
    "segments": [
      "seg-065"
    ]
  },
  "1_艺术风格/经典流派": {
    "count": 30,
    "segments": [
      "seg-060"
    ]
  },
  "1_艺术风格/数字风格": {
    "count": 15,
    "segments": [
      "seg-078"
    ]
  },
  "1_艺术风格/现代潮流": {
    "count": 38,
    "segments": [
      "seg-055"
    ]
  },
  "10_物品道具/日常物品": {
    "count": 79,
    "segments": [
      "seg-039"
    ]
  },
  "10_物品道具/特效元素": {
    "count": 27,
    "segments": [
      "seg-062"
    ]
  },
  "10_物品道具/武器": {
    "count": 95,
    "segments": [
      "seg-031"
    ]
  },
  "11_动植物/动物": {
    "count": 92,
    "segments": [
      "seg-033"
    ]
  },
  "11_动植物/植物": {
    "count": 22,
    "segments": [
      "seg-069"
    ]
  },
  "12_负面提示/画质缺陷": {
    "count": 24,
    "segments": [
      "seg-066"
    ]
  },
  "12_负面提示/内容过滤": {
    "count": 15,
    "segments": [
      "seg-079"
    ]
  },
  "2_构图视角/构图方式": {
    "count": 6,
    "segments": [
      "seg-094"
    ]
  },
  "2_构图视角/镜头距离": {
    "count": 2,
    "segments": [
      "seg-102"
    ]
  },
  "2_构图视角/视角方向": {
    "count": 3,
    "segments": [
      "seg-097"
    ]
  },
  "3_人物主体/人数性别": {
    "count": 18,
    "segments": [
      "seg-073"
    ]
  },
  "3_人物主体/体型年龄": {
    "count": 33,
    "segments": [
      "seg-059"
    ]
  },
  "3_人物主体/职业身份": {
    "count": 81,
    "segments": [
      "seg-037"
    ]
  },
  "3_人物主体/种族": {
    "count": 44,
    "segments": [
      "seg-053"
    ]
  },
  "4_发型发色/发型": {
    "count": 3,
    "segments": [
      "seg-098"
    ]
  },
  "5_五官表情/表情": {
    "count": 38,
    "segments": [
      "seg-056"
    ]
  },
  "5_五官表情/面部细节": {
    "count": 14,
    "segments": [
      "seg-082"
    ]
  },
  "5_五官表情/眼睛": {
    "count": 2,
    "segments": [
      "seg-103"
    ]
  },
  "6_服装配饰/配饰": {
    "count": 24,
    "segments": [
      "seg-067"
    ]
  },
  "6_服装配饰/上身服装": {
    "count": 15,
    "segments": [
      "seg-080"
    ]
  },
  "6_服装配饰/下身服装": {
    "count": 11,
    "segments": [
      "seg-086"
    ]
  },
  "6_服装配饰/鞋袜": {
    "count": 15,
    "segments": [
      "seg-081"
    ]
  },
  "7_场景背景/城市建筑": {
    "count": 14,
    "segments": [
      "seg-083"
    ]
  },
  "7_场景背景/时间天气": {
    "count": 36,
    "segments": [
      "seg-057"
    ]
  },
  "7_场景背景/室内场景": {
    "count": 16,
    "segments": [
      "seg-077"
    ]
  },
  "7_场景背景/自然场景": {
    "count": 19,
    "segments": [
      "seg-071"
    ]
  },
  "8_色彩光线/光照": {
    "count": 10,
    "segments": [
      "seg-087"
    ]
  },
  "8_色彩光线/色调": {
    "count": 8,
    "segments": [
      "seg-091"
    ]
  },
  "9_动作姿态/动态动作": {
    "count": 70,
    "segments": [
      "seg-040"
    ]
  },
  "9_动作姿态/手部姿态": {
    "count": 13,
    "segments": [
      "seg-084"
    ]
  },
  "9_动作姿态/站坐姿态": {
    "count": 5,
    "segments": [
      "seg-096"
    ]
  },
  "背景": {
    "count": 18,
    "segments": [
      "seg-074"
    ]
  },
  "城市": {
    "count": 6,
    "segments": [
      "seg-095"
    ]
  },
  "耳朵": {
    "count": 54,
    "segments": [
      "seg-047"
    ]
  },
  "发型": {
    "count": 898,
    "segments": [
      "seg-021"
    ]
  },
  "方向与视线": {
    "count": 27,
    "segments": [
      "seg-063"
    ]
  },
  "服装": {
    "count": 4594,
    "segments": [
      "seg-015",
      "seg-016"
    ]
  },
  "符号/特殊标签": {
    "count": 81,
    "segments": [
      "seg-038"
    ]
  },
  "构图": {
    "count": 51,
    "segments": [
      "seg-050"
    ]
  },
  "构图与镜头": {
    "count": 273,
    "segments": [
      "seg-024"
    ]
  },
  "花卉植物": {
    "count": 182,
    "segments": [
      "seg-026"
    ]
  },
  "画面格式": {
    "count": 120,
    "segments": [
      "seg-028"
    ]
  },
  "画面元素": {
    "count": 8,
    "segments": [
      "seg-092"
    ]
  },
  "画面遮挡": {
    "count": 10,
    "segments": [
      "seg-088"
    ]
  },
  "画质": {
    "count": 12,
    "segments": [
      "seg-085"
    ]
  },
  "建筑": {
    "count": 94,
    "segments": [
      "seg-032"
    ]
  },
  "角色与作品": {
    "count": 36033,
    "segments": [
      "seg-000",
      "seg-001",
      "seg-002",
      "seg-003",
      "seg-004",
      "seg-005",
      "seg-006",
      "seg-007",
      "seg-008",
      "seg-009",
      "seg-010",
      "seg-011",
      "seg-012",
      "seg-013",
      "seg-014"
    ]
  },
  "颈部": {
    "count": 65,
    "segments": [
      "seg-044"
    ]
  },
  "面部特征": {
    "count": 1101,
    "segments": [
      "seg-019"
    ]
  },
  "敏感分级": {
    "count": 359,
    "segments": [
      "seg-023"
    ]
  },
  "人物动作": {
    "count": 1054,
    "segments": [
      "seg-020"
    ]
  },
  "人物类型": {
    "count": 153,
    "segments": [
      "seg-027"
    ]
  },
  "色彩": {
    "count": 27,
    "segments": [
      "seg-064"
    ]
  },
  "上半身": {
    "count": 97,
    "segments": [
      "seg-029"
    ]
  },
  "身体特征": {
    "count": 3514,
    "segments": [
      "seg-017",
      "seg-018"
    ]
  },
  "身体装饰": {
    "count": 17,
    "segments": [
      "seg-076"
    ]
  },
  "食物 · breads": {
    "count": 53,
    "segments": [
      "seg-048"
    ]
  },
  "食物 · condiments": {
    "count": 18,
    "segments": [
      "seg-075"
    ]
  },
  "食物 · dairy": {
    "count": 23,
    "segments": [
      "seg-068"
    ]
  },
  "食物 · drink": {
    "count": 62,
    "segments": [
      "seg-045"
    ]
  },
  "食物 · fruit": {
    "count": 89,
    "segments": [
      "seg-034"
    ]
  },
  "食物 · meal": {
    "count": 97,
    "segments": [
      "seg-030"
    ]
  },
  "食物 · meat": {
    "count": 53,
    "segments": [
      "seg-049"
    ]
  },
  "食物 · sweets": {
    "count": 201,
    "segments": [
      "seg-025"
    ]
  },
  "食物 · vegetable": {
    "count": 69,
    "segments": [
      "seg-041"
    ]
  },
  "视觉效果": {
    "count": 40,
    "segments": [
      "seg-054"
    ]
  },
  "室内环境": {
    "count": 36,
    "segments": [
      "seg-058"
    ]
  },
  "室外环境": {
    "count": 61,
    "segments": [
      "seg-046"
    ]
  },
  "天空天气": {
    "count": 19,
    "segments": [
      "seg-072"
    ]
  },
  "头部装饰": {
    "count": 83,
    "segments": [
      "seg-035"
    ]
  },
  "透视与视角": {
    "count": 21,
    "segments": [
      "seg-070"
    ]
  },
  "未分类": {
    "count": 66,
    "segments": [
      "seg-042"
    ]
  },
  "物品": {
    "count": 45,
    "segments": [
      "seg-051"
    ]
  },
  "下半身": {
    "count": 83,
    "segments": [
      "seg-036"
    ]
  },
  "鞋袜": {
    "count": 66,
    "segments": [
      "seg-043"
    ]
  },
  "艺术表现": {
    "count": 30,
    "segments": [
      "seg-061"
    ]
  },
  "艺术风格": {
    "count": 371,
    "segments": [
      "seg-022"
    ]
  },
  "艺术风格/绘画媒介": {
    "count": 10,
    "segments": [
      "seg-089"
    ]
  },
  "艺术风格/数字艺术": {
    "count": 3,
    "segments": [
      "seg-099"
    ]
  },
  "自然环境": {
    "count": 45,
    "segments": [
      "seg-052"
    ]
  },
  "NSFW/暧昧氛围": {
    "count": 3,
    "segments": [
      "seg-100"
    ]
  },
  "NSFW/暴露程度": {
    "count": 7,
    "segments": [
      "seg-093"
    ]
  },
  "NSFW/氛围暗示": {
    "count": 1,
    "segments": [
      "seg-105"
    ]
  },
  "NSFW/亲密互动": {
    "count": 2,
    "segments": [
      "seg-104"
    ]
  }
};
